package Vistas;

import Persistencia.FacturaCRUD;
import Persistencia.VehiculoCRUD;
import Validadaciones.NegocioCliente;
import Validadaciones.NegocioEmpleado;
import Validadaciones.VehiculoNegocio;
import entidades.Cliente;
import entidades.Empleado;
import entidades.Factura;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author jssa3
 */
public class FrmVenderVehiculo extends javax.swing.JFrame {

    Cliente cliente;
    Empleado empleado;
    NegocioCliente nCliente = new NegocioCliente();
    NegocioEmpleado nEmpleado = new NegocioEmpleado();
    Factura factura;
    FacturaCRUD fCRUD = new FacturaCRUD();
    VehiculoNegocio nVehiculo = new VehiculoNegocio();
    VehiculoCRUD vCRUD = new VehiculoCRUD();

    public FrmVenderVehiculo() {
        initComponents();
        jcMarcas.setSelectedIndex(0);
        jcModelos.setSelectedIndex(0);
        nVehiculo.cargarComboMarcas(jcMarcas);
        nVehiculo.cargarComboModelo(jcModelos);
        txtNombreCliente.setEditable(false);
        tbVehiculos.setModel(vCRUD.listadoVehiculos(tbVehiculos));
        //TAMBIEN SE DEBE PERMITIR BUSCAR POR MARCAS MODELOS O ESTADO(USADO O NUEVO)
        //SE TIENE LA TABLA DE TODOS LOS VEHICULOS PERO SI EL CLIENTE DESEA BUSCAR POR
        //UN VEHICULO EN ESPECIFICO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbVehiculos = new javax.swing.JTable();
        btnVendet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDocumentoCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcMarcas = new javax.swing.JComboBox<>();
        jcModelos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDocumentoVendedor = new javax.swing.JTextField();
        btnInicio = new javax.swing.JButton();
        jsCantidad = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbVehiculos);

        btnVendet.setText("VENDER");
        btnVendet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendetActionPerformed(evt);
            }
        });

        jLabel2.setText("SELECCIONE UN VEHICULO");

        jLabel1.setText("BUSCAR DOCUMENTO DEL CLIENTE");

        jLabel3.setText("NOMBRE DEL CLIENTE");

        jcMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE..." }));

        jcModelos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE...." }));

        jLabel5.setText("MARCAS");

        jLabel6.setText("MODELOS");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("DOCUMENTO VENDEDOR");

        btnInicio.setText("INICIO");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        jLabel7.setText("CANTIDAD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(97, 97, 97)
                .addComponent(jLabel6)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel2)
                                .addGap(112, 112, 112)
                                .addComponent(jcMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcModelos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVendet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(19, 19, 19)
                                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDocumentoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jsCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnInicio)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnInicio)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jsCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtDocumentoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcModelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVendet)
                            .addComponent(btnBuscar))
                        .addGap(81, 81, 81)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVendetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendetActionPerformed
        Object valorCelda = tbVehiculos.getValueAt(tbVehiculos.getSelectedRow(), tbVehiculos.getSelectedColumn());
        System.out.println("celda: " + valorCelda);
        if (txtDocumentoCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "CAMPOS REQUERIDOS", "FORMATO INVALIDO", 2);
        } else {
            cliente = new Cliente();
            cliente = nCliente.validarExistencia(txtDocumentoCliente.getText());
            if (cliente == null) {
                JOptionPane.showMessageDialog(rootPane, "Cliente no existe");
            } else {
                empleado = new Empleado();
                empleado = nEmpleado.validarExistencia(txtDocumentoVendedor.getText());
                if (empleado == null) {
                    JOptionPane.showMessageDialog(rootPane, "Empleado no existe");
                } else {
                    Date fechaFacturacion = new Date();
                    java.sql.Date fechaInicio = new java.sql.Date(fechaFacturacion.getTime());
                    factura = new Factura();
                    factura.setId_cliente(cliente.getIdCliente());
                    factura.setId_producto((int) valorCelda);
                    factura.setCantidad((int) jsCantidad.getValue());
                    factura.setTipoTransaccion(2);
                    factura.setFechaMoviento(fechaInicio);
                    factura.setId_empleado(empleado.getIdEmpleado());
                    boolean creada = fCRUD.crearFacturaVenta(factura);
                    if (creada) {
                        boolean exitoso = vCRUD.vehiculoVendido(2, factura.getId_producto());
                        if (exitoso) {
                            JOptionPane.showMessageDialog(rootPane, "Venta realizada con exito");
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "No se pudo registrar", "Error", 2);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnVendetActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int marca = jcMarcas.getSelectedIndex();
        int modelo = jcModelos.getSelectedIndex();
        if (jcMarcas.getSelectedIndex() != 0 && jcModelos.getSelectedIndex() == 0) {
            tbVehiculos.setModel(vCRUD.buscarXmarca(marca));
        } else if (jcModelos.getSelectedIndex() != 0) {
            tbVehiculos.setModel(vCRUD.buscarXmodelo(modelo));

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        this.setVisible(false);
        FrmPrincipal principal = new FrmPrincipal(0);
        principal.setVisible(true);
        principal.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVenderVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVenderVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVenderVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVenderVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmVenderVehiculo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnVendet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcMarcas;
    private javax.swing.JComboBox<String> jcModelos;
    private javax.swing.JSpinner jsCantidad;
    private javax.swing.JTable tbVehiculos;
    private javax.swing.JTextField txtDocumentoCliente;
    private javax.swing.JTextField txtDocumentoVendedor;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
